---
version: '3.5'

networks:
    kafkanet:
      driver: bridge
      driver_opts:
         com.docker.network.driver.mtu: 8192
      ipam:
         config:
            - subnet: 172.26.0.0/16
              gateway: 172.26.0.1
services:
  kerberos: 
    image: jairsjunior/kerberos-docker:0.0.4
    hostname: kerberos
    container_name: kerberos
    environment: 
        - REALM=KERBEROS.KERBEROS-DOCKER_DEFAULT
        - DOMAIN_REALM=kerberos.kerberos-docker_default
        - KERB_MASTER_KEY=masterkey
        - KERB_ADMIN_USER=admin
        - KERB_ADMIN_PASS=admin
        - SEARCH_DOMAINS=search.consul kerberos.kerberos-docker_default
    volumes: 
        - ./kerberos-data:/volumes/kerberos:Z
        - ./kerberos-keytabs:/volumes/keytabs:Z
        - ./kerberos-users:/volumes/users:Z
    networks:
      kafkanet:
        ipv4_address: 172.26.0.254

  broker.kerberos:
    depends_on:
      - kerberos
    image: confluentinc/cp-kafka:7.3.2
    hostname: broker.kerberos.kafka-kerberos_default
    container_name: broker.kerberos
    networks:
      kafkanet:
        ipv4_address: 172.26.0.250
    ports:
      - "9093:9093"
      - "9092:9092"
      - "9997:9997"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT'
      KAFKA_LISTENERS: 'PLAINTEXT://broker.kerberos:29092,CONTROLLER://broker.kerberos:29093,PLAINTEXT_HOST://0.0.0.0:9092,SASL_PLAINTEXT://broker.kerberos:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker.kerberos:29092,PLAINTEXT_HOST://localhost:9092,SASL_PLAINTEXT://broker.kerberos:9093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=broker.kerberos.kerberos.kafka-kerberos_default -Dcom.sun.management.jmxremote.rmi.port=9997
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf -Djava.security.krb5.conf=/etc/kafka/krb5.conf "
      KAFKA_NODE_ID: 1
      KAFKA_SASL_KERBEROS_SERVICE_NAME: kafka
      KAFKA_SASL_ENABLED_MECHANISMS: GSSAPI
      KAFKA_LOG_RETENTION_MS: 259200000
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker.kerberos:29093'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./update_run.sh:/tmp/update_run.sh:Z
      - ./kafka-jaas/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf:Z
      - ./kerberos-keytabs/broker.kerberos.kafka-kerberos_default.keytab:/etc/security/keytabs/broker.kerberos.kafka-kerberos_default.keytab:Z
      - ./kerberos-data/krb5.conf:/etc/kafka/krb5.conf:Z
    command: "bash -c 'if [ ! -f /tmp/update_run.sh ]; then echo \"ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/update_run.sh && /etc/confluent/docker/run ; fi'"


  # kafka-ui.kerberos:
  #   hostname: kafka-ui.kerberos
  #   container_name: kafka-ui.kerberos
  #   image: provectuslabs/kafka-ui:v0.5.0
  #   networks:
  #     kafkanet:
  #       ipv4_address: 172.26.0.251
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - broker.kerberos
  #     #- schema-registry.kerberos
  #     #- kafka-connect0
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: SASL_PLAINTEXT://broker.kerberos:9093
  #     KAFKA_CLUSTERS_0_METRICS_PORT: 9997
  #     KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry.kerberos:8081
  #     KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
  #     KAFKA_CLUSTERS_0_PROPERTIES_SASL_KERBEROS_SERVICE_NAME: 'kafka'
  #     KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: GSSAPI
  #     KAFKA_CLUSTERS_0_PROPERTIES_KERBEROS_SERVICE_NAME: kafka
  #     KAFKA_CLUSTERS_0_PROPERTIES_KERBEROS_PARAMS:  -Djava.security.auth.login.config=/home/kafkaui/kafka_ui_jaas.conf -Djava.security.krb5.conf=/home/kafkaui/krb5.conf -Dsun.security.krb5.debug=true
  #     KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'com.sun.security.auth.module.Krb5LoginModule required useTicketCache=false;'
  #     KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: 'SASL_PLAINTEXT'
  #     JAVA_OPTS: -Djava.security.auth.login.config=/home/kafkaui/kafka_ui_jaas.conf -Djava.security.krb5.conf=/home/kafkaui/krb5.conf -Dsun.security.krb5.debug=true
  #     #JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka-ui.kerberos -Dcom.sun.management.jmxremote.rmi.port=9997 -Djava.security.auth.login.config=/etc/kafka-ui/kafka_ui_jaas.conf -Djava.security.krb5.conf=/etc/kafka-ui/krb5.conf
  #     #CUB_CLASSPATH: /etc/confluent/docker/docker-utils.jar:/usr/share/java/kafka-ui/krb5loginmodule-wrapper-0.0.1.jar -Djava.security.auth.login.config=/etc/kafka-ui/kafka_ui_jaas.conf -Djava.security.krb5.conf=/etc/kafka-ui/krb5.conf
  #   volumes:
  #           - ./kafka-jaas/kafka_ui_jaas.conf:/home/kafkaui/kafka_ui_jaas.conf:Z
  #           - ./kerberos-data/krb5.conf:/home/kafkaui/krb5.conf:Z
  #           - ./kerberos-keytabs/kafka-ui.kerberos.keytab:/home/kafkaui/kafka-ui.kerberos.keytab:Z
  #           - ./kafka-jaas/producer.properties:/home/kafkaui/producer.properties:Z
  #           - ./kafka-jaas/consumer.properties:/home/kafkaui/consumer.properties:Z
  #           - ./libs/krb5loginmodule-wrapper-0.0.1.jar:/usr/share/java/kafka-ui/krb5loginmodule-wrapper-0.0.1.jar:Z
  
  #     #KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect.kerberos:8083
  #     #KAFKA_CLUSTERS_0_KSQLDBSERVER: http://ksqldb:8088

  # schema-registry.kerberos:
  #   depends_on:
  #     - broker.kerberos
  #   image: confluentinc/cp-schema-registry:5.3.1
  #   networks:
  #      kafkanet:
  #        ipv4_address: 172.26.0.252
  #   ports:
  #     - 8081:8081
  #   environment:
  #     SCHEMA_REGISTRY_HOST_NAME: schema-registry.kerberos
  #     SCHEMA_REGISTRY_LISTENERS: http://schema-registry.kerberos:8081
  #     SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: "http"
  #     SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: DEBUG
  #     SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
  #     SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: SASL_PLAINTEXT://broker.kerberos:9093
  #     SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SASL_PLAINTEXT
  #     SCHEMA_REGISTRY_KAFKASTORE_SASL_KERBEROS_SERVICE_NAME: kafka
  #     SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: GSSAPI
  #     SCHEMA_REGISTRY_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=49999 -Djava.security.auth.login.config=/etc/schema-registry/kafka_schema_registry_jaas.conf -Djava.security.krb5.conf=/etc/schema-registry/krb5.conf
  #     CUB_CLASSPATH: /etc/confluent/docker/docker-utils.jar:/usr/share/java/schema-registry/krb5loginmodule-wrapper-0.0.1.jar -Djava.security.auth.login.config=/etc/schema-registry/kafka_schema_registry_jaas.conf -Djava.security.krb5.conf=/etc/schema-registry/krb5.conf
  #   volumes:
  #     - ./kafka-jaas/kafka_schema_registry_jaas.conf:/etc/schema-registry/kafka_schema_registry_jaas.conf:Z
  #     - ./kerberos-data/krb5.conf:/etc/schema-registry/krb5.conf:Z
  #     - ./libs/krb5loginmodule-wrapper-0.0.1.jar:/usr/share/java/schema-registry/krb5loginmodule-wrapper-0.0.1.jar:Z
